main/default/objects/EmailValidationParameter__mdt/EmailValidationParameter__mdt.object-meta.xml
<CustomObject>
    <description>Contains custom metadata for streamlining email workflows in any sobject. One metadata record contains specifications about the SObject Type, what status picklist to use, and which email template is required to proceed in the mapped stage.</description>
    <label>Email Validation Parameter</label>
    <pluralLabel>Email Validation Parameters</pluralLabel>
</CustomObject>

main/default/objects/EmailValidationParameter__mdt/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <description>Error Message that is displayed when a user tries to proceed in the process without having send the required email template.</description>
    <inlineHelpText>Error Message that is displayed when a user tries to proceed in the process without having send the required email template.</inlineHelpText>
    <label>Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/classes/EmailValidation_Test.cls
@isTest
public class EmailValidation_Test {

    @TestSetup
    static void setupData(){
        Account acc = new Account(
                Name = 'TestAcc' + System.now()
        );
        insert acc;

        Opportunity oppOld = new Opportunity(
                Name = 'TestOpp' + System.now(),
                AccountId = acc.Id,
                CloseDate = System.today(),
                StageName = 'Prospecting'
        );

        Opportunity oppNew = new Opportunity(
                Name = 'TestOpp' + System.now(),
                AccountId = acc.Id,
                CloseDate = System.today(),
                StageName = 'Pledged'
        );

        insert new List<SObject>{oppOld, oppNew};

        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs(thisUser){
            EmailTemplate testTemplate = new EmailTemplate(
                    Name = 'TestTemplateForProjectProcess',
                    FolderId = thisUser.Id,
                    TemplateType ='custom',
                    Body = 'Test',
                    DeveloperName = 'TestTemplateForProjectProcess',
                    IsActive = true
            );
            insert testTemplate;

            EmailMessage testMessage = new EmailMessage(
                    EmailTemplateId = testTemplate.Id,
                    FromAddress = 'test@trailhead.de',
                    ToAddress = 'test@linkedin.de',
                    Status = '3',
                    Subject = 'Das ist ein Test',
                    RelatedToId = oppNew.Id
            );
            insert testMessage;

        }
    }

    @isTest
    static void processEmailValidation_Test(){
        EmailTemplate testTemplate = [SELECT Id FROM EmailTemplate WHERE Name = 'TestTemplateForOppProcess'];
        EmailMessage testMessage = [SELECT Id, RelatedToId FROM EmailMessage LIMIT 1];
        List<Opportunity> testOpps = [SELECT Id, StageName FROM Opportunity ORDER BY Name DESC];
        Map<Id, Opportunity> oldMapOpps = new Map<Id,Opportunity>{testOpps[1].Id => testOpps[0]};
        Map<Id, Opportunity> newMapOpps = new Map<Id,Opportunity>{testOpps[1].Id => testOpps[1]};

        Test.startTest();
        EmailValidation.processEmailValidation(newMapOpps, oldMapOpps, 'StageName');
        Test.stopTest();

        Assert.areEqual(EmailValidationParameter__mdt.getInstance(testOpps[0].StageName).ErrorMessage__c, testOpps[1].getErrors()[0].getMessage());
    }
}